tap 'homebrew/cask-fonts'

cask 'font-caskaydia-cove-nerd-font'
cask 'spotify'

brew 'asdf'
brew 'neovim'
brew 'rcm'
brew 'the_silver_searcher'
brew 'fzf'
brew 'ripgrep'
brew 'httpie'
brew 'git-delta'
brew 'zplug'
brew 'libpq'
brew 'zsh'
