return {}
-- return {
--   {
--   'github/copilot.vim',
--   config = function ()
--     vim.keymap.set('i', '<C-A>', 'copilot#Accept("\\<CR>")', {
--       expr = true,
--       replace_keycodes = false
--     })
--     vim.keymap.set('i', '<C-L>', '<Plug>(copilot-accept-word)', {})
--     vim.g.copilot_no_tab_map = true
--   end
--   },
--   {
--     'CopilotC-Nvim/CopilotChat.nvim',
--     dependencies = {
--       { "github/copilot.vim" },
--       { "nvim-lua/plenary.nvim", branch = "master" },
--     },
--     build = "make tiktoken",
--     opts = {},
--   }
-- }
